### ISSUE TITLE
put locale folder in the same folder of the examples run (e.g. ex-03)

### ISSUE THREAD

**Issue by jpmarindiaz** [datasketch/shi18ny#20]
We would expect users generally not to modify the default `locale` folder for the app translations.

It would be easier for users to check the code of the app and how it works right in the same folder they are running the app from, and not having to navigate to the tests folder to see what is happening.

**Comment by lenafm** [comment]
At the moment, every example that uses custom translations (ex02, ex04, and ex05) has a `locale` folder in the example folder. So in each of the folders (`ex02-basic_custom`, `ex04-translate_data_upload_custom`, `ex05-translate_plot_labels`) there's the `app.R` file and the `locale` folder. 

Is that not what you would expect?
