### ISSUE TITLE
FYI - potential useful backend support in package traduire

### ISSUE THREAD

**Issue by richfitz** [datasketch/shi18ny#25]
Full disclosure, I am one of the authors of tradiure.

We've been working on backend support for i18n work (not in the context of shiny apps) and developed a package called traduire (https://github.com/reside-ic/traduire) which wraps the [i18next js library](https://www.i18next.com/), and so includes lots of nice support (pluralisation, context specific translation, in theory support for RTL languages etc). Depending on your goals you might find it useful.

Just an FYI - if you're happier developing your own engine please disregard

**Comment by jpmarindiaz** [comment]
Thanks for the info. 
I don't really feel like building a whole new engine right now :) but rather providing a simple interface for users to provide their own translations easily.
So perhaps in the futures it would be nice to provide a way for users to choose their own engine including traudire. 
For now in the roadmap we have including d3 like locales for dates and currencies using  https://github.com/dreamRs/d3.format
For now we'll wait and see how the package evolves.

I will add a link to `traduire` in the README for other users to check it out.
